### ISSUE TITLE
しおしおさんのかっこいい感じの実装を

### ISSUE THREAD

**Issue by yyYank** [yyYank/Kebab#1]
<del>パクりたい</del>

リスペクトしたい

forkしてくれたやつ
https://github.com/siosio/Kebab

多分ここらへんオシャレ
https://github.com/siosio/Kebab/blob/master/src/main/kotlin/kebab/Configuration.kt

と思ってたけどもっといっぱい実装変わってた
https://github.com/siosio/Kebab/commit/93e7b41797465ef0fc81c1c93e14f991c22eec4b

**Comment by siosio** [comment]
|дﾟ)ﾁﾗｯ

**Comment by yyYank** [comment]
ぎくっ

**Comment by siosio** [comment]
:beers:
